'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'..','pc','index.html'),'utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);
const w={};new Function('window','document','navigator','performance',scripts[0]+'\n'+scripts[1].replace("window.addEventListener('DOMContentLoaded',()=>{ const game=new Game(); window.__ENDLESS_DEFENDERS__=game; game.init(); });","window.__audit={Game,DEFENDER_CONTRACTS,DEFAULT_SAVE};"))(w,{}, {language:'ru'},{now:()=>0});
const {Game,DEFENDER_CONTRACTS,DEFAULT_SAVE}=w.__audit;
const g=Object.create(Game.prototype);g.save=JSON.parse(JSON.stringify(DEFAULT_SAVE));g.lang='ru';g.t={unitPrism:'Призма',unitNova:'Нова',unitEmber:'Эмбер',unitVolt:'Вольт',unitChrono:'Хроно'};
g.audio={fragment(){},unlock(){}};g.track=()=>{};g.toast=()=>{};g.persist=()=>{};g.renderHome=()=>{};g.renderCollection=()=>{};g.celebrateReward=()=>{};
let tests=0;function test(name,fn){assert(fn(),name);tests++;console.log('PASS '+name);}
const items=Object.entries(DEFENDER_CONTRACTS),expected={prism:[2500,18,2,3],nova:[4500,30,3,4],ember:[8000,50,4,4],volt:[13000,80,5,4],chrono:[20000,125,6,5]};
test('All permanent prices and fragment counts untouched',()=>items.every(([id,c])=>[c.shards,c.gems,c.parts,c.pity].every((v,i)=>v===expected[id][i])));
test('Unlock order still chained',()=>items.map(([id,c])=>c.requires).join(',')===',prism,nova,ember,volt');
test('Eligible boss forecast matches the 30-wave cycle',()=>JSON.stringify(items.map(([id])=>g.eligibleContractBossWaves(id)))===JSON.stringify([[40,70,100],[50,80,110],[60,90,120],[100,130,160],[120,150,180]]));
test('No fragments from wrong boss',()=>{g.rollDefenderFragment('leech',50);return g.save.defenderParts.prism===0;});
test('Pity guarantees prism by six eligible wins',()=>{for(let i=0;i<6;i++)g.rollDefenderFragment('aegis',40);return g.save.defenderParts.prism===2;});
test('Late pity guarantees five volt fragments in 20 eligible wins',()=>{g.save.unlocked.push('prism','nova','ember');for(let i=0;i<20;i++)g.rollDefenderFragment('aegis',100);return g.save.defenderParts.volt===5;});
test('Late pity guarantees six chrono fragments in 30 eligible wins',()=>{g.save.unlocked.push('volt');for(let i=0;i<30;i++)g.rollDefenderFragment('singularity',120);return g.save.defenderParts.chrono===6;});
test('Contract fragment cap respected',()=>{for(let i=0;i<10;i++)g.rollDefenderFragment('singularity',120);return g.save.defenderParts.chrono===6;});
test('Cannot unlock defender without currency despite full fragments',()=>{g.save.bestWave=120;g.unlockDefender('chrono');return !g.save.unlocked.includes('chrono');});
test('Save schema preserved',()=>html.includes('out.version=21'));
console.log(tests+' economy contract checks passed');
