'use strict';
// Read-only Laboratory purchase funding indicator; costs and unlocks must be unchanged.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pc=fs.readFileSync(path.join(__dirname,'..','pc','index.html'),'utf8');
const mobile=fs.readFileSync(path.join(__dirname,'..','iphone','index.html'),'utf8');
const scripts=s=>[...s.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const a=scripts(pc),b=scripts(mobile);
assert.equal(a[1],b[1],'PC and mobile combat scripts diverged');
const hook="window.addEventListener('DOMContentLoaded',()=>{ const game=new Game(); window.__ENDLESS_DEFENDERS__=game; game.init(); });";
assert(a[1].includes(hook),'Cannot extract game');
const elements=new Map();
function fake(id){if(!elements.has(id))elements.set(id,{innerHTML:''});return elements.get(id);}
const document={getElementById:fake,querySelectorAll:()=>[]};
const win={};
new Function('window','document','navigator','performance',a[0]+'\n'+a[1].replace(hook,'window.__labQa={Game,DEFAULT_SAVE,LABS,TEXT};'))(
  win,document,{language:'ru'}, {now:()=>0});
const {Game,DEFAULT_SAVE,LABS,TEXT}=win.__labQa;
const g=Object.create(Game.prototype);
g.save=JSON.parse(JSON.stringify(DEFAULT_SAVE));
g.lang='ru';g.t=TEXT.ru;
const key=Object.keys(LABS)[0],level=g.save.lab[key]||0,cost=g.labUpgradeCost(key,level);
assert(cost>1,'Expected a non-trivial Laboratory cost');
const before=JSON.stringify(g.save);
g.save.shards=Math.floor(cost/2);
const current=JSON.stringify(g.save);
let v=g.labFunding(key,level);
assert.equal(v.cost,cost);
assert.equal(v.available,Math.floor(cost/2));
assert.equal(v.missing,cost-g.save.shards);
assert.equal(v.can,false);
assert(v.percent>=0&&v.percent<100);
g.renderLab();
let html=fake('labList').innerHTML;
assert(html.includes('data-lab-funding="'+key+'"'));
assert(html.includes('role="progressbar"'));
assert(html.includes('aria-valuemax="'+cost+'"'));
assert(html.includes('aria-valuenow="'+Math.floor(cost/2)+'"'));
assert(html.includes('На следующий уровень'));
assert(html.includes('Не хватает'));
assert.equal(JSON.stringify(g.save),current,'Rendering Laboratory changed player progress');
g.save.shards=cost+500;
v=g.labFunding(key,level);
assert.equal(v.missing,0);
assert.equal(v.percent,100);
assert.equal(v.can,true);
g.renderLab();
html=fake('labList').innerHTML;
assert(html.includes('lab-funding ready'),'Affordable upgrade did not show ready progress');
assert(html.includes('aria-valuenow="'+cost+'"'),'Progress meter was not capped to the upgrade cost');
g.lang='en';g.t=TEXT.en;
g.renderLab();
assert(fake('labList').innerHTML.includes('Next level'),'Missing English progress label');
g.save.lab[key]=LABS[key].max;
v=g.labFunding(key,g.save.lab[key]);
assert.equal(v.max,true);
assert.equal(v.can,false);
g.renderLab();
assert(!fake('labList').innerHTML.includes('data-lab-funding="'+key+'"'),'Maxed out Laboratory needs no funding bar');
assert(g.save.shards>0&&JSON.parse(before).version===21,'Save schema or currency modified unexpectedly');
console.log('PASS Laboratory funding UX read-only, affordability, limits, localization and PC/mobile parity');
