'use strict';
// Ads/background must not inflate playtime or skip returning-player retention.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const pc=fs.readFileSync(path.join(__dirname,'..','pc','index.html'),'utf8');
const iphone=fs.readFileSync(path.join(__dirname,'..','iphone','index.html'),'utf8');
const scripts=s=>[...s.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
assert.equal(scripts(pc)[1],scripts(iphone)[1],'Browser game scripts diverged');
const begin=pc.indexOf('  class Game {'),end=pc.indexOf("\n\n  window.addEventListener('DOMContentLoaded'",begin);
assert(begin>=0&&end>begin,'Game class not found');
const doc={hidden:false};
let clock=1000000,day='2026-10-08',paused=0,resumed=0;
const Game=new Function('document','now','dayKey','return ('+pc.slice(begin,end).trim()+')')(
  doc,()=>clock,()=>day);
const g=Object.create(Game.prototype);
g.save={analytics:{totalPlayMs:0,firstSessionDay:day,playDays:[day],events:{},retention:{d1:false,d3:false,d7:false}}};
g.sessionActiveAt=clock-10000;
g.run={holdFire:true,aim:{x:500,y:200}};
g.inRun=true;g.paused=false;g.pauseOverlay=false;g.externalPause=false;g.externalPauseWasPaused=false;
g.externalPauseReasons=new Set();
g.setRmbBoost=()=>{};
g.pauseInternal=()=>{paused++;};
g.bridge={gameplayStop:()=>{},gameplayStart:()=>{resumed++;}};
g.audio={resume:()=>{}};
g.track=event=>{const e=g.save.analytics.events;e[event]=(e[event]||0)+1;};
g.handleExternalPause(true,'ad');
assert.equal(g.save.analytics.totalPlayMs,10000,'Ad pause must checkpoint active playtime');
assert.equal(g.sessionActiveAt,0,'Paused clock must stop');
assert.equal(g.run.holdFire,false,'Ad pause must release input');
clock+=60000;
doc.hidden=true;g.handleExternalPause(true,'visibility');
assert.equal(g.save.analytics.totalPlayMs,10000,'Nested visibility pause double-counted playtime');
doc.hidden=false;day='2026-10-09';
g.resumePlaytime(); // Browser visibility callback fires before ad closes.
g.handleExternalPause(false,'visibility');
assert.equal(g.sessionActiveAt,0,'Ad still open must block resumed clock');
assert.equal(g.save.analytics.events.session_day||0,0,'Retention recorded before the game resumed');
clock+=30000;
g.handleExternalPause(false,'ad');
assert.equal(g.sessionActiveAt,clock,'Active clock must restart after final pause ends');
assert.equal(g.save.analytics.totalPlayMs,10000,'Ad time leaked into active playtime');
assert.equal(g.save.analytics.events.session_day,1,'Returning next day must count');
assert.equal(g.save.analytics.events.retention_d1,1,'Returning D1 player not detected');
assert.equal(g.save.analytics.retention.d1,true);
g.resumePlaytime();
assert.equal(g.save.analytics.events.session_day,1,'Repeated resume duplicated retention');
assert.equal(g.save.analytics.events.retention_d1,1,'Repeated resume duplicated D1');
clock+=2000;
g.checkpointPlaytime();
assert.equal(g.save.analytics.totalPlayMs,12000,'Clock must exclude 90s paused time');
assert.equal(resumed,1,'Combat must resume only once after ad/visibility pause');
assert(paused>=2,'External pause must still run combat pause logic');
console.log('PASS ad/visibility time exclusion, nested pause, D1 return and PC/iPhone parity');
