extends RefCounted

# generated by tools/blender/vehicles_hd.py — HD vehicle atlas (384 px cells, draw at 0.5).
const ATLAS = "res://art/vehicles/vehicles_hd_v1.png"
const CELL = 384
const KINDS = {
    "lada_blue":0,
    "lada_red":1,
    "lada_white":2,
    "lada_burnt":3,
    "car_on_blocks":4,
    "uaz_ambulance":5,
    "uaz_burnt":6,
    "btr80":7,
    "t72_wreck":8,
    "mi8_wreck":9,
    "kamaz_bowser":10,
    "gen_trailer":11,
    "cryo_semi":12,
    "vent_head":13,
    "cooling_fans":14,
    "light_mast":15,
    "hazmat_drums":16,
    "body_bags":17,
    "decon_tunnel":18,
    "container_stack":19,
    "crater":20,
    "sandbag_wall":21,
    "lattice_mast":22,
    "dragon_teeth":23,
    "cable_spool_yard":24,
    "rail_cart":25,
    "po2_fence":26,
    "po2_fence_v":27,
    "gate_pillar":28,
    "hospital_sign":29,
    "quarantine_sign":30,
}
