"""Precompute opaque bounds of atlas cells used by measured set-piece placement
(main_script_mod._hr_used_rect), so the game never decompresses a whole atlas
in the middle of a chunk transition.

    python3 tools/sprite_used_rects.py <project_dir>
writes world/sprite_used_rects.gd
"""
import os
import sys
import numpy as np
from PIL import Image

ATLASES = [
    ('art/vehicles/vehicles_hd_v1.png', 384, 384),
    ('settlement_props_v1.png', 192, 192),
    ('art/high_risk/hr_props_v1.png', 192, 192),
    ('poi_props_v1.png', 192, 128),
]


def cells(path, cw, ch, P):
    im = Image.open(os.path.join(P, path)).convert('RGBA')
    a = np.array(im)[..., 3]
    if cw is None:                  # poi atlas: square cells of the image height
        cw = ch = im.height
    out = {}
    for y in range(0, im.height - ch + 1, ch):
        for x in range(0, im.width - cw + 1, cw):
            c = a[y:y + ch, x:x + cw] > 0
            ys, xs = np.nonzero(c)
            r = (0, 0, 0, 0) if len(xs) == 0 else (int(xs.min()), int(ys.min()), int(xs.max() - xs.min() + 1), int(ys.max() - ys.min() + 1))
            out['%d,%d,%d,%d' % (x, y, cw, ch)] = r
    return out


def build(P):
    lines = ['extends RefCounted', '', '# GENERATED by tools/sprite_used_rects.py - opaque bounds per atlas cell.', 'const RECTS = {']
    for path, cw, ch in ATLASES:
        if not os.path.exists(os.path.join(P, path)):
            continue
        for k, r in cells(path, cw, ch, P).items():
            lines.append('    "res://%s|%s":Rect2(%d,%d,%d,%d),' % (path, k, *r))
    lines.append('}')
    with open(os.path.join(P, 'world', 'sprite_used_rects.gd'), 'w') as f:
        f.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    build(sys.argv[1] if len(sys.argv) > 1 else '.')
